### ISSUE TITLE
HI I got this error code when I tried to run it. I'll try to decrypt it later

### ISSUE THREAD

**Issue by CavHaunch** [mkornyev/PyMusic#1]
Traceback (most recent call last):
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 410, in main
    run()
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2019.4.12954\pythonFiles\lib\python\ptvsd\__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\<user>\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\<user>\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\<user>\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\<user>\_WrkDir\Python Playground\PyMusic\Root.py", line 354, in <module>
    run(1100, 700)
  File "c:\Users\<user>\_WrkDir\Python Playground\PyMusic\Root.py", line 339, in run
    init(data, root)
  File "c:\Users\<user>\_WrkDir\Python Playground\PyMusic\Root.py", line 148, in init
    data.Qnote = PhotoImage(file='Qnote.gif')
  File "C:\Users\<user>\AppData\Local\Continuum\anaconda3\lib\tkinter\__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\<user>\AppData\Local\Continuum\anaconda3\lib\tkinter\__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "Qnote.gif": no such file or directory

**Comment by Davidbillingsley** [comment]
@CavHaunch I think I see what the error is.  I need to test the code a bit first to verify it.  If i am right your issue is due to your variable is / can only be used by the def function that it is contained within.
